// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"

// WebsiteChecker is an autogenerated mock type for the WebsiteChecker type
type WebsiteChecker struct {
	mock.Mock
}

// CreateStatus provides a mock function with given fields: ctx, url
func (_m *WebsiteChecker) CreateStatus(ctx context.Context, url string) (string, error) {
	ret := _m.Called(ctx, url)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, url)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
